// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package cardpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MedCardClient is the client API for MedCard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MedCardClient interface {
	// Получает список карт пациентов.
	//
	// Получает список карт пациентов с возможностью пагинации. Возвращает GetCardListResponse, содержащий список карт и информацию о пагинации.
	GetCardList(ctx context.Context, in *GetCardListRequest, opts ...grpc.CallOption) (*GetCardListResponse, error)
	// Создает новую карту пациента.
	//
	// Создает новую карту пациента. Возвращает CreateCardResponse с идентификатором созданной карты.
	CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*CreateCardResponse, error)
	// Получает карту пациента.
	//
	// Получает карту пациента по идентификатору. Возвращает GetCardResponse с информацией о карте.
	GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*PatientCard, error)
	// Обновляет существующую карту пациента.
	//
	// Обновляет существующую карту пациента по идентификатору. Возвращает пустой ответ в случае успешного обновления.
	UpdateCard(ctx context.Context, in *UpdateCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Частично обновляет карту пациента.
	//
	// Частично обновляет карту пациента по идентификатору с использованием маски полей. Возвращает обновленный объект PatientCard.
	PatchCard(ctx context.Context, in *PatchCardRequest, opts ...grpc.CallOption) (*PatientCard, error)
	// Удаляет карту пациента.
	//
	// Удаляет карту пациента по идентификатору. Возвращает пустой ответ в случае успешного удаления.
	DeleteCard(ctx context.Context, in *DeleteCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type medCardClient struct {
	cc grpc.ClientConnInterface
}

func NewMedCardClient(cc grpc.ClientConnInterface) MedCardClient {
	return &medCardClient{cc}
}

func (c *medCardClient) GetCardList(ctx context.Context, in *GetCardListRequest, opts ...grpc.CallOption) (*GetCardListResponse, error) {
	out := new(GetCardListResponse)
	err := c.cc.Invoke(ctx, "/card.service.MedCard/GetCardList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medCardClient) CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*CreateCardResponse, error) {
	out := new(CreateCardResponse)
	err := c.cc.Invoke(ctx, "/card.service.MedCard/CreateCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medCardClient) GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*PatientCard, error) {
	out := new(PatientCard)
	err := c.cc.Invoke(ctx, "/card.service.MedCard/GetCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medCardClient) UpdateCard(ctx context.Context, in *UpdateCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/card.service.MedCard/UpdateCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medCardClient) PatchCard(ctx context.Context, in *PatchCardRequest, opts ...grpc.CallOption) (*PatientCard, error) {
	out := new(PatientCard)
	err := c.cc.Invoke(ctx, "/card.service.MedCard/PatchCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medCardClient) DeleteCard(ctx context.Context, in *DeleteCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/card.service.MedCard/DeleteCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MedCardServer is the server API for MedCard service.
// All implementations must embed UnimplementedMedCardServer
// for forward compatibility
type MedCardServer interface {
	// Получает список карт пациентов.
	//
	// Получает список карт пациентов с возможностью пагинации. Возвращает GetCardListResponse, содержащий список карт и информацию о пагинации.
	GetCardList(context.Context, *GetCardListRequest) (*GetCardListResponse, error)
	// Создает новую карту пациента.
	//
	// Создает новую карту пациента. Возвращает CreateCardResponse с идентификатором созданной карты.
	CreateCard(context.Context, *CreateCardRequest) (*CreateCardResponse, error)
	// Получает карту пациента.
	//
	// Получает карту пациента по идентификатору. Возвращает GetCardResponse с информацией о карте.
	GetCard(context.Context, *GetCardRequest) (*PatientCard, error)
	// Обновляет существующую карту пациента.
	//
	// Обновляет существующую карту пациента по идентификатору. Возвращает пустой ответ в случае успешного обновления.
	UpdateCard(context.Context, *UpdateCardRequest) (*emptypb.Empty, error)
	// Частично обновляет карту пациента.
	//
	// Частично обновляет карту пациента по идентификатору с использованием маски полей. Возвращает обновленный объект PatientCard.
	PatchCard(context.Context, *PatchCardRequest) (*PatientCard, error)
	// Удаляет карту пациента.
	//
	// Удаляет карту пациента по идентификатору. Возвращает пустой ответ в случае успешного удаления.
	DeleteCard(context.Context, *DeleteCardRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedMedCardServer()
}

// UnimplementedMedCardServer must be embedded to have forward compatible implementations.
type UnimplementedMedCardServer struct {
}

func (UnimplementedMedCardServer) GetCardList(context.Context, *GetCardListRequest) (*GetCardListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCardList not implemented")
}
func (UnimplementedMedCardServer) CreateCard(context.Context, *CreateCardRequest) (*CreateCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCard not implemented")
}
func (UnimplementedMedCardServer) GetCard(context.Context, *GetCardRequest) (*PatientCard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCard not implemented")
}
func (UnimplementedMedCardServer) UpdateCard(context.Context, *UpdateCardRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCard not implemented")
}
func (UnimplementedMedCardServer) PatchCard(context.Context, *PatchCardRequest) (*PatientCard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchCard not implemented")
}
func (UnimplementedMedCardServer) DeleteCard(context.Context, *DeleteCardRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCard not implemented")
}
func (UnimplementedMedCardServer) mustEmbedUnimplementedMedCardServer() {}

// UnsafeMedCardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MedCardServer will
// result in compilation errors.
type UnsafeMedCardServer interface {
	mustEmbedUnimplementedMedCardServer()
}

func RegisterMedCardServer(s grpc.ServiceRegistrar, srv MedCardServer) {
	s.RegisterService(&MedCard_ServiceDesc, srv)
}

func _MedCard_GetCardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedCardServer).GetCardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.service.MedCard/GetCardList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedCardServer).GetCardList(ctx, req.(*GetCardListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedCard_CreateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedCardServer).CreateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.service.MedCard/CreateCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedCardServer).CreateCard(ctx, req.(*CreateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedCard_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedCardServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.service.MedCard/GetCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedCardServer).GetCard(ctx, req.(*GetCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedCard_UpdateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedCardServer).UpdateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.service.MedCard/UpdateCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedCardServer).UpdateCard(ctx, req.(*UpdateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedCard_PatchCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedCardServer).PatchCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.service.MedCard/PatchCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedCardServer).PatchCard(ctx, req.(*PatchCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedCard_DeleteCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedCardServer).DeleteCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.service.MedCard/DeleteCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedCardServer).DeleteCard(ctx, req.(*DeleteCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MedCard_ServiceDesc is the grpc.ServiceDesc for MedCard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MedCard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "card.service.MedCard",
	HandlerType: (*MedCardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCardList",
			Handler:    _MedCard_GetCardList_Handler,
		},
		{
			MethodName: "CreateCard",
			Handler:    _MedCard_CreateCard_Handler,
		},
		{
			MethodName: "GetCard",
			Handler:    _MedCard_GetCard_Handler,
		},
		{
			MethodName: "UpdateCard",
			Handler:    _MedCard_UpdateCard_Handler,
		},
		{
			MethodName: "PatchCard",
			Handler:    _MedCard_PatchCard_Handler,
		},
		{
			MethodName: "DeleteCard",
			Handler:    _MedCard_DeleteCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "card.proto",
}
