gateway:
  env: DEV
  host: localhost
  http: 8080

auth:
  env: DEV
  host: localhost
  grpc: 50055
  http: 8081

token:
  access_time: 1m
  refresh_time: 5m

med:
  env: DEV
  host: localhost
  grpc: 50056
  http: 8082

uzi:
  env: DEV
  host: localhost
  grpc: 50057
  http: 8083
  
s3:
  env: DEV
  host: localhost
  grpc: 50058
