// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package s3pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// S3UploadClient is the client API for S3Upload service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type S3UploadClient interface {
	UploadAndSplitUziFile(ctx context.Context, opts ...grpc.CallOption) (S3Upload_UploadAndSplitUziFileClient, error)
	GetByPathImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (S3Upload_GetByPathImageClient, error)
}

type s3UploadClient struct {
	cc grpc.ClientConnInterface
}

func NewS3UploadClient(cc grpc.ClientConnInterface) S3UploadClient {
	return &s3UploadClient{cc}
}

func (c *s3UploadClient) UploadAndSplitUziFile(ctx context.Context, opts ...grpc.CallOption) (S3Upload_UploadAndSplitUziFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &S3Upload_ServiceDesc.Streams[0], "/yir.s3upload.S3Upload/UploadAndSplitUziFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &s3UploadUploadAndSplitUziFileClient{stream}
	return x, nil
}

type S3Upload_UploadAndSplitUziFileClient interface {
	Send(*ImageStream) error
	CloseAndRecv() (*UploadUziFileResponse, error)
	grpc.ClientStream
}

type s3UploadUploadAndSplitUziFileClient struct {
	grpc.ClientStream
}

func (x *s3UploadUploadAndSplitUziFileClient) Send(m *ImageStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *s3UploadUploadAndSplitUziFileClient) CloseAndRecv() (*UploadUziFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadUziFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *s3UploadClient) GetByPathImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (S3Upload_GetByPathImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &S3Upload_ServiceDesc.Streams[1], "/yir.s3upload.S3Upload/GetByPathImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &s3UploadGetByPathImageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type S3Upload_GetByPathImageClient interface {
	Recv() (*ImageStream, error)
	grpc.ClientStream
}

type s3UploadGetByPathImageClient struct {
	grpc.ClientStream
}

func (x *s3UploadGetByPathImageClient) Recv() (*ImageStream, error) {
	m := new(ImageStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// S3UploadServer is the server API for S3Upload service.
// All implementations must embed UnimplementedS3UploadServer
// for forward compatibility
type S3UploadServer interface {
	UploadAndSplitUziFile(S3Upload_UploadAndSplitUziFileServer) error
	GetByPathImage(*GetImageRequest, S3Upload_GetByPathImageServer) error
	mustEmbedUnimplementedS3UploadServer()
}

// UnimplementedS3UploadServer must be embedded to have forward compatible implementations.
type UnimplementedS3UploadServer struct {
}

func (UnimplementedS3UploadServer) UploadAndSplitUziFile(S3Upload_UploadAndSplitUziFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadAndSplitUziFile not implemented")
}
func (UnimplementedS3UploadServer) GetByPathImage(*GetImageRequest, S3Upload_GetByPathImageServer) error {
	return status.Errorf(codes.Unimplemented, "method GetByPathImage not implemented")
}
func (UnimplementedS3UploadServer) mustEmbedUnimplementedS3UploadServer() {}

// UnsafeS3UploadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to S3UploadServer will
// result in compilation errors.
type UnsafeS3UploadServer interface {
	mustEmbedUnimplementedS3UploadServer()
}

func RegisterS3UploadServer(s grpc.ServiceRegistrar, srv S3UploadServer) {
	s.RegisterService(&S3Upload_ServiceDesc, srv)
}

func _S3Upload_UploadAndSplitUziFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(S3UploadServer).UploadAndSplitUziFile(&s3UploadUploadAndSplitUziFileServer{stream})
}

type S3Upload_UploadAndSplitUziFileServer interface {
	SendAndClose(*UploadUziFileResponse) error
	Recv() (*ImageStream, error)
	grpc.ServerStream
}

type s3UploadUploadAndSplitUziFileServer struct {
	grpc.ServerStream
}

func (x *s3UploadUploadAndSplitUziFileServer) SendAndClose(m *UploadUziFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *s3UploadUploadAndSplitUziFileServer) Recv() (*ImageStream, error) {
	m := new(ImageStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _S3Upload_GetByPathImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(S3UploadServer).GetByPathImage(m, &s3UploadGetByPathImageServer{stream})
}

type S3Upload_GetByPathImageServer interface {
	Send(*ImageStream) error
	grpc.ServerStream
}

type s3UploadGetByPathImageServer struct {
	grpc.ServerStream
}

func (x *s3UploadGetByPathImageServer) Send(m *ImageStream) error {
	return x.ServerStream.SendMsg(m)
}

// S3Upload_ServiceDesc is the grpc.ServiceDesc for S3Upload service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var S3Upload_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yir.s3upload.S3Upload",
	HandlerType: (*S3UploadServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadAndSplitUziFile",
			Handler:       _S3Upload_UploadAndSplitUziFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetByPathImage",
			Handler:       _S3Upload_GetByPathImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "s3upload.proto",
}
