// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package medworkerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MedWorkersClient is the client API for MedWorkers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MedWorkersClient interface {
	//Получение списка медработников
	//
	//Возвращает список со всеми медработниками
	GetMedWorkers(ctx context.Context, in *GetMedworkerRequest, opts ...grpc.CallOption) (*GetMedworkerListResponse, error)
	//Полное обновление информации о медработнике
	//
	//
	UpdateMedWorker(ctx context.Context, in *UpdateMedWorkerRequest, opts ...grpc.CallOption) (*UpdateMedWorkerResponse, error)
	//Получение информации о медработнике по ID
	//
	//Возвращает информацию о медработнике по ID
	GetMedWorkerByID(ctx context.Context, in *GetMedMedWorkerByIDRequest, opts ...grpc.CallOption) (*GetMedWorkerByIDResponse, error)
	//Частичное обновление информации о медработнике
	//
	//
	PatchMedWorker(ctx context.Context, in *PatchMedWorkerRequest, opts ...grpc.CallOption) (*UpdateMedWorkerResponse, error)
	//Добавление медработника
	//
	//
	AddMedWorker(ctx context.Context, in *AddMedWorkerRequest, opts ...grpc.CallOption) (*AddMedWorkerResponse, error)
	//Получение пациентов, прикрепленных к врачу
	//
	//Вернет пациентов, их карточки и главого врача
	GetPatientsByMedWorker(ctx context.Context, in *GetPatientsByMedWorkerRequest, opts ...grpc.CallOption) (*GetPatientsByMedWorkerResponse, error)
}

type medWorkersClient struct {
	cc grpc.ClientConnInterface
}

func NewMedWorkersClient(cc grpc.ClientConnInterface) MedWorkersClient {
	return &medWorkersClient{cc}
}

func (c *medWorkersClient) GetMedWorkers(ctx context.Context, in *GetMedworkerRequest, opts ...grpc.CallOption) (*GetMedworkerListResponse, error) {
	out := new(GetMedworkerListResponse)
	err := c.cc.Invoke(ctx, "/service.medworkers.MedWorkers/GetMedWorkers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medWorkersClient) UpdateMedWorker(ctx context.Context, in *UpdateMedWorkerRequest, opts ...grpc.CallOption) (*UpdateMedWorkerResponse, error) {
	out := new(UpdateMedWorkerResponse)
	err := c.cc.Invoke(ctx, "/service.medworkers.MedWorkers/UpdateMedWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medWorkersClient) GetMedWorkerByID(ctx context.Context, in *GetMedMedWorkerByIDRequest, opts ...grpc.CallOption) (*GetMedWorkerByIDResponse, error) {
	out := new(GetMedWorkerByIDResponse)
	err := c.cc.Invoke(ctx, "/service.medworkers.MedWorkers/GetMedWorkerByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medWorkersClient) PatchMedWorker(ctx context.Context, in *PatchMedWorkerRequest, opts ...grpc.CallOption) (*UpdateMedWorkerResponse, error) {
	out := new(UpdateMedWorkerResponse)
	err := c.cc.Invoke(ctx, "/service.medworkers.MedWorkers/PatchMedWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medWorkersClient) AddMedWorker(ctx context.Context, in *AddMedWorkerRequest, opts ...grpc.CallOption) (*AddMedWorkerResponse, error) {
	out := new(AddMedWorkerResponse)
	err := c.cc.Invoke(ctx, "/service.medworkers.MedWorkers/AddMedWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medWorkersClient) GetPatientsByMedWorker(ctx context.Context, in *GetPatientsByMedWorkerRequest, opts ...grpc.CallOption) (*GetPatientsByMedWorkerResponse, error) {
	out := new(GetPatientsByMedWorkerResponse)
	err := c.cc.Invoke(ctx, "/service.medworkers.MedWorkers/GetPatientsByMedWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MedWorkersServer is the server API for MedWorkers service.
// All implementations must embed UnimplementedMedWorkersServer
// for forward compatibility
type MedWorkersServer interface {
	//Получение списка медработников
	//
	//Возвращает список со всеми медработниками
	GetMedWorkers(context.Context, *GetMedworkerRequest) (*GetMedworkerListResponse, error)
	//Полное обновление информации о медработнике
	//
	//
	UpdateMedWorker(context.Context, *UpdateMedWorkerRequest) (*UpdateMedWorkerResponse, error)
	//Получение информации о медработнике по ID
	//
	//Возвращает информацию о медработнике по ID
	GetMedWorkerByID(context.Context, *GetMedMedWorkerByIDRequest) (*GetMedWorkerByIDResponse, error)
	//Частичное обновление информации о медработнике
	//
	//
	PatchMedWorker(context.Context, *PatchMedWorkerRequest) (*UpdateMedWorkerResponse, error)
	//Добавление медработника
	//
	//
	AddMedWorker(context.Context, *AddMedWorkerRequest) (*AddMedWorkerResponse, error)
	//Получение пациентов, прикрепленных к врачу
	//
	//Вернет пациентов, их карточки и главого врача
	GetPatientsByMedWorker(context.Context, *GetPatientsByMedWorkerRequest) (*GetPatientsByMedWorkerResponse, error)
	mustEmbedUnimplementedMedWorkersServer()
}

// UnimplementedMedWorkersServer must be embedded to have forward compatible implementations.
type UnimplementedMedWorkersServer struct {
}

func (UnimplementedMedWorkersServer) GetMedWorkers(context.Context, *GetMedworkerRequest) (*GetMedworkerListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedWorkers not implemented")
}
func (UnimplementedMedWorkersServer) UpdateMedWorker(context.Context, *UpdateMedWorkerRequest) (*UpdateMedWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMedWorker not implemented")
}
func (UnimplementedMedWorkersServer) GetMedWorkerByID(context.Context, *GetMedMedWorkerByIDRequest) (*GetMedWorkerByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedWorkerByID not implemented")
}
func (UnimplementedMedWorkersServer) PatchMedWorker(context.Context, *PatchMedWorkerRequest) (*UpdateMedWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchMedWorker not implemented")
}
func (UnimplementedMedWorkersServer) AddMedWorker(context.Context, *AddMedWorkerRequest) (*AddMedWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMedWorker not implemented")
}
func (UnimplementedMedWorkersServer) GetPatientsByMedWorker(context.Context, *GetPatientsByMedWorkerRequest) (*GetPatientsByMedWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPatientsByMedWorker not implemented")
}
func (UnimplementedMedWorkersServer) mustEmbedUnimplementedMedWorkersServer() {}

// UnsafeMedWorkersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MedWorkersServer will
// result in compilation errors.
type UnsafeMedWorkersServer interface {
	mustEmbedUnimplementedMedWorkersServer()
}

func RegisterMedWorkersServer(s grpc.ServiceRegistrar, srv MedWorkersServer) {
	s.RegisterService(&MedWorkers_ServiceDesc, srv)
}

func _MedWorkers_GetMedWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedworkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedWorkersServer).GetMedWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.medworkers.MedWorkers/GetMedWorkers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedWorkersServer).GetMedWorkers(ctx, req.(*GetMedworkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedWorkers_UpdateMedWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMedWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedWorkersServer).UpdateMedWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.medworkers.MedWorkers/UpdateMedWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedWorkersServer).UpdateMedWorker(ctx, req.(*UpdateMedWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedWorkers_GetMedWorkerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedMedWorkerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedWorkersServer).GetMedWorkerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.medworkers.MedWorkers/GetMedWorkerByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedWorkersServer).GetMedWorkerByID(ctx, req.(*GetMedMedWorkerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedWorkers_PatchMedWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchMedWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedWorkersServer).PatchMedWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.medworkers.MedWorkers/PatchMedWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedWorkersServer).PatchMedWorker(ctx, req.(*PatchMedWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedWorkers_AddMedWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMedWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedWorkersServer).AddMedWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.medworkers.MedWorkers/AddMedWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedWorkersServer).AddMedWorker(ctx, req.(*AddMedWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedWorkers_GetPatientsByMedWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPatientsByMedWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedWorkersServer).GetPatientsByMedWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.medworkers.MedWorkers/GetPatientsByMedWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedWorkersServer).GetPatientsByMedWorker(ctx, req.(*GetPatientsByMedWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MedWorkers_ServiceDesc is the grpc.ServiceDesc for MedWorkers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MedWorkers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.medworkers.MedWorkers",
	HandlerType: (*MedWorkersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMedWorkers",
			Handler:    _MedWorkers_GetMedWorkers_Handler,
		},
		{
			MethodName: "UpdateMedWorker",
			Handler:    _MedWorkers_UpdateMedWorker_Handler,
		},
		{
			MethodName: "GetMedWorkerByID",
			Handler:    _MedWorkers_GetMedWorkerByID_Handler,
		},
		{
			MethodName: "PatchMedWorker",
			Handler:    _MedWorkers_PatchMedWorker_Handler,
		},
		{
			MethodName: "AddMedWorker",
			Handler:    _MedWorkers_AddMedWorker_Handler,
		},
		{
			MethodName: "GetPatientsByMedWorker",
			Handler:    _MedWorkers_GetPatientsByMedWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}
