version: "3"

vars:
  VENDOR_PROTOGEN: "../vendor.protogen"

#TODO: написать проверки в коде при подключении ко всему
env:
  GOOSE_DRIVER: postgres
  GOOSE_DBSTRING: postgres://postgres:1234@localhost:5432/uzidb
  DB_DSN: postgres://postgres:1234@localhost:5432/uzidb
  S3_ENDPOINT: localhost:9000
  S3_TOKEN_ACCESS: BLAD0h1rTDPG70DQ7PUd
  S3_TOKEN_SECRET: qtbVnWFWlu7hpIGt8A3HPYpOPiHF6cECHzaicigz
  BROKER_ADDRS: localhost:19092

tasks:
  codegen:
    vars:
      proto_libs:
        sh: find {{.VENDOR_PROTOGEN}} -mindepth 1 -maxdepth 1 -type d | xargs echo
      proto_files:
        sh: find proto -type f -name "*.proto" | xargs echo

    cmds:
      - for: { var: proto_files }
        cmd: >
          protoc
          -I {{dir .ITEM}}
          {{range $lib := splitList " " .proto_libs}}-I {{$lib}} {{end}}
          --experimental_allow_proto3_optional
          --go_out . --go-grpc_out .
          {{.ITEM}}
  style:
    cmds:
      - go fmt ./...
      - goimports -w .
      - gofumpt -l -w .

  build:
    cmds:
      - task: codegen
      - task: style
      - go build -v -o bin/service cmd/service/main.go

  run:
    cmds:
      - task: build
      - ./bin/service

  migration-up:
    cmds:
      - goose -dir db/migrations up

  migration-down:
    cmds:
      - goose -dir db/migrations down
