// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UziAPIClient is the client API for UziAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UziAPIClient interface {
	// Добавить uzi
	InsertUzi(ctx context.Context, in *Uzi, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Получить uzi
	GetUzi(ctx context.Context, in *UziIdRequest, opts ...grpc.CallOption) (*Uzi, error)
	// Получить uziinfo
	GetUziInfo(ctx context.Context, in *UziIdRequest, opts ...grpc.CallOption) (*UziInfo, error)
	// Обновить uziinfo
	//
	// **ID при обновлении будет игнорироваться**
	UpdateUziInfo(ctx context.Context, in *UpdateUziRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Получить image && segments на image && formation segment'ов
	GetImageWithSegments(ctx context.Context, in *ImageIdRequest, opts ...grpc.CallOption) (*ImageWithSegments, error)
	// Добавить formation + segments
	InsertFormationWithSegments(ctx context.Context, in *InsertFormationWithSegmentsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Получить formation + segments
	GetFormationWithSegments(ctx context.Context, in *FormationIdRequest, opts ...grpc.CallOption) (*FormationWithSegments, error)
	// Обновить formation
	//
	// **ID при обновлении будет игнорироваться**
	UpdateFormation(ctx context.Context, in *UpdateFormationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Получить список девайсов
	GetDeviceList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDeviceListResponse, error)
}

type uziAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewUziAPIClient(cc grpc.ClientConnInterface) UziAPIClient {
	return &uziAPIClient{cc}
}

func (c *uziAPIClient) InsertUzi(ctx context.Context, in *Uzi, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/yir.uzi.UziAPI/InsertUzi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uziAPIClient) GetUzi(ctx context.Context, in *UziIdRequest, opts ...grpc.CallOption) (*Uzi, error) {
	out := new(Uzi)
	err := c.cc.Invoke(ctx, "/yir.uzi.UziAPI/GetUzi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uziAPIClient) GetUziInfo(ctx context.Context, in *UziIdRequest, opts ...grpc.CallOption) (*UziInfo, error) {
	out := new(UziInfo)
	err := c.cc.Invoke(ctx, "/yir.uzi.UziAPI/GetUziInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uziAPIClient) UpdateUziInfo(ctx context.Context, in *UpdateUziRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/yir.uzi.UziAPI/UpdateUziInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uziAPIClient) GetImageWithSegments(ctx context.Context, in *ImageIdRequest, opts ...grpc.CallOption) (*ImageWithSegments, error) {
	out := new(ImageWithSegments)
	err := c.cc.Invoke(ctx, "/yir.uzi.UziAPI/GetImageWithSegments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uziAPIClient) InsertFormationWithSegments(ctx context.Context, in *InsertFormationWithSegmentsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/yir.uzi.UziAPI/InsertFormationWithSegments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uziAPIClient) GetFormationWithSegments(ctx context.Context, in *FormationIdRequest, opts ...grpc.CallOption) (*FormationWithSegments, error) {
	out := new(FormationWithSegments)
	err := c.cc.Invoke(ctx, "/yir.uzi.UziAPI/GetFormationWithSegments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uziAPIClient) UpdateFormation(ctx context.Context, in *UpdateFormationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/yir.uzi.UziAPI/UpdateFormation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uziAPIClient) GetDeviceList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDeviceListResponse, error) {
	out := new(GetDeviceListResponse)
	err := c.cc.Invoke(ctx, "/yir.uzi.UziAPI/GetDeviceList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UziAPIServer is the server API for UziAPI service.
// All implementations must embed UnimplementedUziAPIServer
// for forward compatibility
type UziAPIServer interface {
	// Добавить uzi
	InsertUzi(context.Context, *Uzi) (*emptypb.Empty, error)
	// Получить uzi
	GetUzi(context.Context, *UziIdRequest) (*Uzi, error)
	// Получить uziinfo
	GetUziInfo(context.Context, *UziIdRequest) (*UziInfo, error)
	// Обновить uziinfo
	//
	// **ID при обновлении будет игнорироваться**
	UpdateUziInfo(context.Context, *UpdateUziRequest) (*emptypb.Empty, error)
	// Получить image && segments на image && formation segment'ов
	GetImageWithSegments(context.Context, *ImageIdRequest) (*ImageWithSegments, error)
	// Добавить formation + segments
	InsertFormationWithSegments(context.Context, *InsertFormationWithSegmentsRequest) (*emptypb.Empty, error)
	// Получить formation + segments
	GetFormationWithSegments(context.Context, *FormationIdRequest) (*FormationWithSegments, error)
	// Обновить formation
	//
	// **ID при обновлении будет игнорироваться**
	UpdateFormation(context.Context, *UpdateFormationRequest) (*emptypb.Empty, error)
	// Получить список девайсов
	GetDeviceList(context.Context, *emptypb.Empty) (*GetDeviceListResponse, error)
	mustEmbedUnimplementedUziAPIServer()
}

// UnimplementedUziAPIServer must be embedded to have forward compatible implementations.
type UnimplementedUziAPIServer struct {
}

func (UnimplementedUziAPIServer) InsertUzi(context.Context, *Uzi) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertUzi not implemented")
}
func (UnimplementedUziAPIServer) GetUzi(context.Context, *UziIdRequest) (*Uzi, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUzi not implemented")
}
func (UnimplementedUziAPIServer) GetUziInfo(context.Context, *UziIdRequest) (*UziInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUziInfo not implemented")
}
func (UnimplementedUziAPIServer) UpdateUziInfo(context.Context, *UpdateUziRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUziInfo not implemented")
}
func (UnimplementedUziAPIServer) GetImageWithSegments(context.Context, *ImageIdRequest) (*ImageWithSegments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImageWithSegments not implemented")
}
func (UnimplementedUziAPIServer) InsertFormationWithSegments(context.Context, *InsertFormationWithSegmentsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertFormationWithSegments not implemented")
}
func (UnimplementedUziAPIServer) GetFormationWithSegments(context.Context, *FormationIdRequest) (*FormationWithSegments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFormationWithSegments not implemented")
}
func (UnimplementedUziAPIServer) UpdateFormation(context.Context, *UpdateFormationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFormation not implemented")
}
func (UnimplementedUziAPIServer) GetDeviceList(context.Context, *emptypb.Empty) (*GetDeviceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceList not implemented")
}
func (UnimplementedUziAPIServer) mustEmbedUnimplementedUziAPIServer() {}

// UnsafeUziAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UziAPIServer will
// result in compilation errors.
type UnsafeUziAPIServer interface {
	mustEmbedUnimplementedUziAPIServer()
}

func RegisterUziAPIServer(s grpc.ServiceRegistrar, srv UziAPIServer) {
	s.RegisterService(&UziAPI_ServiceDesc, srv)
}

func _UziAPI_InsertUzi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uzi)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UziAPIServer).InsertUzi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yir.uzi.UziAPI/InsertUzi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UziAPIServer).InsertUzi(ctx, req.(*Uzi))
	}
	return interceptor(ctx, in, info, handler)
}

func _UziAPI_GetUzi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UziIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UziAPIServer).GetUzi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yir.uzi.UziAPI/GetUzi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UziAPIServer).GetUzi(ctx, req.(*UziIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UziAPI_GetUziInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UziIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UziAPIServer).GetUziInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yir.uzi.UziAPI/GetUziInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UziAPIServer).GetUziInfo(ctx, req.(*UziIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UziAPI_UpdateUziInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUziRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UziAPIServer).UpdateUziInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yir.uzi.UziAPI/UpdateUziInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UziAPIServer).UpdateUziInfo(ctx, req.(*UpdateUziRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UziAPI_GetImageWithSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UziAPIServer).GetImageWithSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yir.uzi.UziAPI/GetImageWithSegments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UziAPIServer).GetImageWithSegments(ctx, req.(*ImageIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UziAPI_InsertFormationWithSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertFormationWithSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UziAPIServer).InsertFormationWithSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yir.uzi.UziAPI/InsertFormationWithSegments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UziAPIServer).InsertFormationWithSegments(ctx, req.(*InsertFormationWithSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UziAPI_GetFormationWithSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FormationIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UziAPIServer).GetFormationWithSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yir.uzi.UziAPI/GetFormationWithSegments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UziAPIServer).GetFormationWithSegments(ctx, req.(*FormationIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UziAPI_UpdateFormation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFormationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UziAPIServer).UpdateFormation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yir.uzi.UziAPI/UpdateFormation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UziAPIServer).UpdateFormation(ctx, req.(*UpdateFormationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UziAPI_GetDeviceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UziAPIServer).GetDeviceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yir.uzi.UziAPI/GetDeviceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UziAPIServer).GetDeviceList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// UziAPI_ServiceDesc is the grpc.ServiceDesc for UziAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UziAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yir.uzi.UziAPI",
	HandlerType: (*UziAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertUzi",
			Handler:    _UziAPI_InsertUzi_Handler,
		},
		{
			MethodName: "GetUzi",
			Handler:    _UziAPI_GetUzi_Handler,
		},
		{
			MethodName: "GetUziInfo",
			Handler:    _UziAPI_GetUziInfo_Handler,
		},
		{
			MethodName: "UpdateUziInfo",
			Handler:    _UziAPI_UpdateUziInfo_Handler,
		},
		{
			MethodName: "GetImageWithSegments",
			Handler:    _UziAPI_GetImageWithSegments_Handler,
		},
		{
			MethodName: "InsertFormationWithSegments",
			Handler:    _UziAPI_InsertFormationWithSegments_Handler,
		},
		{
			MethodName: "GetFormationWithSegments",
			Handler:    _UziAPI_GetFormationWithSegments_Handler,
		},
		{
			MethodName: "UpdateFormation",
			Handler:    _UziAPI_UpdateFormation_Handler,
		},
		{
			MethodName: "GetDeviceList",
			Handler:    _UziAPI_GetDeviceList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uzi.proto",
}
